### ISSUE TITLE
IPv6 database server

### ISSUE THREAD

**Issue by MLWALK3R** [BigBrotherBot/big-brother-bot#352]
Noticed if we have a AAAA record on our host name B3 will not connect to the SQL server. I can connect directly to the SQL server using IPv6 fine.

**Comment by danielepantaleone** [comment]
Could you post a b3.log showing the problem?

**Comment by MLWALK3R** [comment]
Here is one log from a user reporting issues, I'm going to test it again.
```
=======================================
150912 14:04:02 BOT 'www.bigbrotherbot.net (b3) v1.9.2 [nt] [PoisonIvy] [Win32 standalone]'
150912 14:04:02 BOT 'Python: 2.7.4 (default, Apr 6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]'
150912 14:04:02 BOT 'Default encoding: ascii'
150912 14:04:02 BOT 'Starting Cod6Parser v0.6 for server 94.23.216.127:28960'
150912 14:04:02 BOT '--------------------------------------------'
150912 14:04:02 BOT 'Attempting to connect to database mysql://db_name:******@db-pub.fr.bph.rocks/db_name...'
150912 14:04:03 ERROR 'Database connection failed, working in remote mode: (2003, "Can\'t connect to MySQL server on \'db-pub.fr.bph.rocks\' (10061)") - [(\'b3\\\\storage\\\\database.pyo\', 243, \'connect\', None), (\'b3\\\\storage\\\\database.pyo\', 188, \'getConnection\', None), (\'MySQLdb\\\\__init__.pyo\', 81, \'Connect\', None), (\'MySQLdb\\\\connections.pyo\', 187, \'__init__\', None)]'
150912 14:04:03 BOT 'Game log C:\\TCAFiles\\Users\\user\\656\\m2demo\\games_mp.log'
150912 14:04:03 BOT 'Starting bot reading file C:\\TCAFiles\\Users\\user\\656\\m2demo\\games_mp.log'
150912 14:04:03 BOT 'rcon status Cache Expire Time: [2 sec] Type: [memory]'
150912 14:04:03 VERBOSE "RCON sending (94.23.216.127:28960) 'status'"
150912 14:04:04 BOT 'Loading Plugins (external plugin directory: C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins)'
150912 14:04:04 BOT 'Loading Plugin #1 admin [conf\\plugin_admin.xml]'
150912 14:04:04 BOT 'AdminPlugin: Loading config conf\\plugin_admin.xml for AdminPlugin'
150912 14:04:04 INFO 'AdminPlugin: ------ loading warn_reasons from config file ------'
150912 14:04:04 INFO "AdminPlugin: warn reason 'default' : (60.0, '^7behave yourself')"
150912 14:04:04 INFO "AdminPlugin: warn reason 'generic' : (60.0, '^7')"
150912 14:04:04 INFO 'AdminPlugin: rule9 3 hours \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
150912 14:04:04 INFO 'AdminPlugin: rule8 3 days \t"^3Rule #8: No profanity or offensive language (in any language)" '
150912 14:04:04 INFO 'AdminPlugin: rule3 1 day \t"^3Rule #3: No arguing with admins (listen and learn or leave)" '
150912 14:04:04 INFO 'AdminPlugin: rule2 1 day \t"^3Rule #2: No clan stacking, members must split evenly between the teams" '
150912 14:04:04 INFO 'AdminPlugin: rule1 1.4 week \t"^3Rule #1: No racism of any kind" '
150912 14:04:04 INFO 'AdminPlugin: rule7 1 day \t"^3Rule #7: No advertising or spamming of websites or servers" '
150912 14:04:04 INFO 'AdminPlugin: rule6 1 day \t"^3Rule #6: No recruiting for your clan, your server, or anything else" '
150912 14:04:04 INFO 'AdminPlugin: rule5 1 hour \t"^3Rule #5: No offensive or potentially offensive names, annoying names, or in-game (double caret (^)) color in names" '
150912 14:04:04 INFO 'AdminPlugin: rule4 1 day \t"^3Rule #4: No abusive language or behavior towards admins or other players" '
150912 14:04:04 INFO 'AdminPlugin: adv 1 day \t"^3Rule #7: No advertising or spamming of websites or servers" '
150912 14:04:04 INFO 'AdminPlugin: afk 5 minutes \t"^7you appear to be away from your keyboard" '
150912 14:04:04 INFO 'AdminPlugin: generic 1 hour \t"^7" '
150912 14:04:04 INFO 'AdminPlugin: ci 5 minutes \t"^7connection interupted, reconnect" '
150912 14:04:04 INFO 'AdminPlugin: racism 1.4 week \t"^3Rule #1: No racism of any kind" '
150912 14:04:04 INFO 'AdminPlugin: camp 1 hour \t"^7stop camping or you will be kicked!" '
150912 14:04:04 INFO 'AdminPlugin: sfire 3 hours \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
150912 14:04:04 INFO 'AdminPlugin: color 1 hour \t"^7No in-game (double caret (^)) color in names" '
150912 14:04:04 INFO 'AdminPlugin: tk 1 day \t"^7stop team killing!" '
150912 14:04:04 INFO 'AdminPlugin: nocmd 1 hour \t"^7do not use commands that you do not have access to, try using !help" '
150912 14:04:04 INFO 'AdminPlugin: spec 5 minutes \t"^7spectator too long on full server" '
150912 14:04:04 INFO 'AdminPlugin: lang 3 days \t"^3Rule #8: No profanity or offensive language (in any language)" '
150912 14:04:04 INFO 'AdminPlugin: cuss 3 days \t"^3Rule #8: No profanity or offensive language (in any language)" '
150912 14:04:04 INFO 'AdminPlugin: jerk 1 day \t"^3Rule #4: No abusive language or behavior towards admins or other players" '
150912 14:04:04 INFO 'AdminPlugin: fakecmd 1 hour \t"^7do not use fake commands" '
150912 14:04:04 INFO 'AdminPlugin: rule10 3 days \t"^3Rule #10: Offense players must play for the objective and support their team" '
150912 14:04:04 INFO 'AdminPlugin: stack 1 day \t"^3Rule #2: No clan stacking, members must split evenly between the teams" '
150912 14:04:04 INFO 'AdminPlugin: spawnfire 3 hours \t"^3Rule #9: Do ^1NOT ^3fire at teammates or within 10 seconds of spawning" '
150912 14:04:04 INFO 'AdminPlugin: obj 1 hour \t"^7go for the objective!" '
150912 14:04:04 INFO 'AdminPlugin: name 1 hour \t"^3Rule #5: No offensive or potentially offensive names, annoying names, or in-game (double caret (^)) color in names" '
150912 14:04:04 INFO 'AdminPlugin: language 3 days \t"^3Rule #8: No profanity or offensive language (in any language)" '
150912 14:04:04 INFO 'AdminPlugin: default 1 hour \t"^7behave yourself" '
150912 14:04:04 INFO 'AdminPlugin: profanity 3 days \t"^3Rule #8: No profanity or offensive language (in any language)" '
150912 14:04:04 INFO 'AdminPlugin: spam 1 hour \t"^7do not spam, shut-up!" '
150912 14:04:04 INFO 'AdminPlugin: recruit 1 day \t"^3Rule #6: No recruiting for your clan, your server, or anything else" '
150912 14:04:04 INFO 'AdminPlugin: badname 1 hour \t"^7No offensive, potentially offensive, or annoying names" '
150912 14:04:04 INFO 'AdminPlugin: spectator 5 minutes \t"^7spectator too long on full server" '
150912 14:04:04 INFO 'AdminPlugin: argue 1 day \t"^3Rule #3: No arguing with admins (listen and learn or leave)" '
150912 14:04:04 INFO 'AdminPlugin: -------------- warn_reasons loaded ----------------'
150912 14:04:04 BOT 'Attempting to connect to database mysql://db_name:******@db-pub.fr.bph.rocks/db_name...'
150912 14:04:04 ERROR 'Error loading plugin admin'
Traceback (most recent call last):
File "b3\parser.pyo", line 674, in loadPlugins
File "b3\plugin.pyo", line 56, in __init__
File "b3\plugin.pyo", line 115, in loadConfig
File "b3\plugins\admin.pyo", line 163, in onLoadConfig
File "b3\parser.pyo", line 895, in getGroupLevel
File "b3\decorators.pyo", line 60, in __call__
File "b3\parser.pyo", line 887, in getGroup
File "b3\storage\database.pyo", line 858, in getGroup
AttributeError: 'NoneType' object has no attribute 'getOneRow'
150912 14:04:04 BOT 'Loading Plugin #2 xlrstats [C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\xlrstats.xml]'
150912 14:04:04 INFO 'xlrstats is not a built-in plugin (No module named xlrstats)'
150912 14:04:04 INFO 'trying external plugin directory : C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins'
150912 14:04:04 BOT 'XlrstatsPlugin: Loading config C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\xlrstats.xml for XlrstatsPlugin'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (False) for settings::silent'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (True) for settings::hide_bots'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (True) for settings::exclude_bots'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (2) for settings::assist_timespan'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (10) for settings::damage_assist_release'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (0) for settings::announce'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (1) for settings::keep_time'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_playerstats) for tables::playerstats'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_weaponstats) for tables::weaponstats'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_weaponusage) for tables::weaponusage'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_bodyparts) for tables::bodyparts'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_playerbody) for tables::playerbody'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_opponents) for tables::opponents'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_mapstats) for tables::mapstats'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_playermaps) for tables::playermaps'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_actionstats) for tables::actionstats'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_playeractions) for tables::playeractions'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_history_monthly) for tables::history_monthly'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (xlr_history_weekly) for tables::history_weekly'
150912 14:04:04 DEBUG 'XlrstatsPlugin: Using default value (ctime) for tables::ctime'
150912 14:04:04 DEBUG 'Register Event: Stop Process: XlrstatsPlugin'
150912 14:04:04 DEBUG 'Register Event: Program Exit: XlrstatsPlugin'
150912 14:04:04 BOT 'Plugin xlrstats (2.7.1 - Tim ter Laak / Mark Weirath) loaded'
150912 14:04:04 BOT 'Loading Plugin #3 alteradmin [C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\alteradmin.xml]'
150912 14:04:04 INFO 'alteradmin is not a built-in plugin (No module named alteradmin)'
150912 14:04:04 INFO 'trying external plugin directory : C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins'
150912 14:04:04 BOT 'AlteradminPlugin: Loading config C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\alteradmin.xml for AlteradminPlugin'
150912 14:04:04 DEBUG 'Register Event: Stop Process: AlteradminPlugin'
150912 14:04:04 DEBUG 'Register Event: Program Exit: AlteradminPlugin'
150912 14:04:04 BOT 'Plugin alteradmin (2.19 - iain17) loaded'
150912 14:04:04 BOT 'Loading Plugin #4 fusion [C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\fusion.xml]'
150912 14:04:04 INFO 'fusion is not a built-in plugin (No module named fusion)'
150912 14:04:04 INFO 'trying external plugin directory : C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins'
150912 14:04:04 BOT 'FusionPlugin: Loading config C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\fusion.xml for FusionPlugin'
150912 14:04:04 DEBUG 'Register Event: Stop Process: FusionPlugin'
150912 14:04:04 DEBUG 'Register Event: Program Exit: FusionPlugin'
150912 14:04:04 BOT 'Plugin fusion (1.0.0 - Fl0w) loaded'
150912 14:04:04 BOT 'Loading Plugin #5 firstkill [C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\firstkill.xml]'
150912 14:04:04 INFO 'firstkill is not a built-in plugin (No module named firstkill)'
150912 14:04:04 INFO 'trying external plugin directory : C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins'
150912 14:04:04 BOT 'FirstkillPlugin: Loading config C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins\\conf\\firstkill.xml for FirstkillPlugin'
150912 14:04:04 DEBUG 'Register Event: Stop Process: FirstkillPlugin'
150912 14:04:04 DEBUG 'Register Event: Program Exit: FirstkillPlugin'
150912 14:04:04 BOT 'Plugin firstkill (1.4.1 - PtitBigorneau www.ptitbigorneau.fr) loaded'
150912 14:04:04 BOT 'Loading Plugin #6 duel [C:\\TCAFiles\\Users\\user\\656\\b3\\conf\\plugin_duel.xml]'
150912 14:04:04 INFO 'duel is not a built-in plugin (No module named duel)'
150912 14:04:04 INFO 'trying external plugin directory : C:\\TCAFiles\\Users\\user\\656\\b3\\extplugins'
150912 14:04:04 BOT 'DuelPlugin: Loading config C:\\TCAFiles\\Users\\user\\656\\b3\\conf\\plugin_duel.xml for DuelPlugin'
150912 14:04:04 BOT 'DuelPlugin: No config file found for DuelPlugin. (was not required either)'
150912 14:04:04 DEBUG 'Register Event: Stop Process: DuelPlugin'
150912 14:04:04 DEBUG 'Register Event: Program Exit: DuelPlugin'
150912 14:04:04 BOT 'Plugin duel (1.1 - Courgette) loaded'
150912 14:04:04 BOT 'Loading Plugin publist'
150912 14:04:04 BOT 'PublistPlugin: No config file found for PublistPlugin. (was not required either)'
150912 14:04:04 DEBUG 'Register Event: Stop Process: PublistPlugin'
150912 14:04:04 DEBUG 'Register Event: Program Exit: PublistPlugin'
150912 14:04:04 BOT 'Plugin publist (1.10.2 - ThorN, Courgette) loaded'
150912 14:04:04 DEBUG 'creating the event queue with size 50'
150912 14:04:04 BOT 'Starting parser'
150912 14:04:04 DEBUG 'Client Connected: [-1] World - WORLD ({})'
150912 14:04:04 DEBUG 'Storage: getClient Client<@0:WORLD|WORLD:"World":-1>'
150912 14:04:04 BOT 'Attempting to connect to database mysql://db_name:******@db-pub.fr.bph.rocks/db_name...'
150912 14:04:04 DEBUG "User not found WORLD: 'No client matching guid WORLD in admins_cache'"
150912 14:04:04 BOT 'Client not found in the storage WORLD, create new'
150912 14:04:04 DEBUG 'Storage: setClient Client<@0:WORLD|WORLD:"World":-1>'
150912 14:04:04 DEBUG "Storage: setClient data {'time_add': 1442063044, 'password': '', 'time_edit': 1442063044, 'name': 'World', 'group_bits': 0, 'ip': '', 'greeting': '', 'auto_login': 1, 'connections': 1, 'mask_level': 0, 'login': '', 'guid': 'WORLD', 'pbid': 'WORLD'}"
150912 14:04:04 BOT 'Attempting to connect to database mysql://db_name:******@db-pub.fr.bph.rocks/db_name...'
150912 14:04:04 DEBUG 'Client Authorized: [-1] World - WORLD'
150912 14:04:04 INFO 'map is: mp_rust'
150912 14:04:04 DEBUG 'Forcing server cvar g_logsync to 1'
150912 14:04:04 VERBOSE "RCON sending (94.23.216.127:28960) 'set g_logsync 1'"
150912 14:04:05 VERBOSE "RCON sending (94.23.216.127:28960) 'fs_game'"
150912 14:04:05 DEBUG 'Get cvar fs_game = ["fs_game" is: "^7" default: "^7"\n Domain is any text\n\x00]'
150912 14:04:05 VERBOSE "RCON sending (94.23.216.127:28960) 'fs_basepath'"
150912 14:04:06 DEBUG 'Get cvar fs_basepath = ["fs_basepath" is: "C:\\TCAFiles\\Users\\user\\656^7" default: "C:\\TCAFiles\\Users\\user\\656^7"\n Domain is any text\n\x00]'
150912 14:04:06 DEBUG 'fs_basepath: C:\\TCAFiles\\Users\\user\\656'
150912 14:04:06 VERBOSE "RCON sending (94.23.216.127:28960) 'fs_homepath'"
150912 14:04:07 DEBUG 'Get cvar fs_homepath = ["fs_homepath" is: "C:\\TCAFiles\\Users\\user\\656^7" default: "C:\\TCAFiles\\Users\\user\\656^7"\n Domain is any text\n\x00]'
150912 14:04:07 DEBUG 'fs_homepath: C:\\TCAFiles\\Users\\user\\656'
150912 14:04:07 VERBOSE "RCON sending (94.23.216.127:28960) 'shortversion'"
150912 14:04:08 DEBUG 'Get cvar shortversion = ["shortversion" is: "1.0^7" default: "1.0^7"\n Domain is any text\n\x00]'
150912 14:04:08 DEBUG 'shortversion: 1.0'
150912 14:04:08 DEBUG 'Parser started.'
150912 14:04:08 VERBOSE "RCON sending (94.23.216.127:28960) 'sv_hostname'"
150912 14:04:09 DEBUG 'Get cvar sv_hostname = ["sv_hostname" is: "^2R^7e^1Generation ^3Clan ^6ITA^7" default: "CoD4Host^7"\n Domain is any text\n\x00]'
150912 14:04:09 DEBUG 'sv_hostname: ^2R^7e^1Generation ^3Clan ^6ITA'
150912 14:04:09 BOT 'Starting plugins'
150912 14:04:09 VERBOSE "RCON sending (94.23.216.127:28960) 'say ^7(^2Kil^7ler^1B3^7): ^8www.bigbrotherbot.net ^0(^8b3^0) ^9v1.9.2 [nt] ^9[^3PoisonIvy^9]^3 ^2[ONLINE]'"
150912 14:04:09 INFO 'STDOUT "Error: \'admin\'"'
150912 14:04:09 INFO "STDOUT '\\n'"
150912 14:04:09 ERROR "STDERR 'Traceback (most recent call last):\\n'"
150912 14:04:09 ERROR 'STDERR \' File "b3\\\\__init__.pyo", line 182, in start\\n\''
150912 14:04:09 ERROR 'STDERR \' File "b3\\\\parser.pyo", line 520, in start\\n\''
150912 14:04:09 ERROR 'STDERR \' File "b3\\\\parser.pyo", line 780, in startPlugins\\n\''
150912 14:04:09 ERROR 'STDERR \' File "b3\\\\parser.pyo", line 770, in start_plugin\\n\''
150912 14:04:09 ERROR 'STDERR "KeyError: \'admin\'\\n"'
============================================================================
```
```

**Comment by MLWALK3R** [comment]
Just tested another server with a direct IPv6 address and no commands work

```
0915 19:52:19	BOT    	'Attempting to connect to database mysql://db778:******@2001d0:d:2238::db:1/db778...'
150915 19:52:19	DEBUG	"User not found WORLD: 'No client matching guid WORLD in admins_cache'"
150915 19:52:19	BOT    	'Client not found in the storage WORLD, create new'
150915 19:52:19	DEBUG	'Storage: setClient Client<@0:WORLD|WORLD:"World":-1>'
150915 19:52:19	DEBUG	"Storage: setClient data {'time_add': 1442343139, 'password': '', 'time_edit': 1442343139, 'name': 'World', 'group_bits': 0, 'ip': '', 'greeting': '', 'auto_login': 1, 'connections': 1, 'mask_level': 0, 'login': '', 'guid': 'WORLD', 'pbid': 'WORLD'}"
150915 19:52:19	BOT    	'Attempting to connect to database mysql://db778:******@2001d0:d:2238::db:1/db778...'
150915 19:52:19	DEBUG	'Client Authorized: [-1] World - WORLD'
150915 19:52:19	VERBOSE	"RCON sending (94.23.216.127:28970) 'status'"
150915 19:52:20	VERBOSE	'No readable socket'
150915 19:52:20	DEBUG	'Forcing server cvar g_logsync to 1'
150915 19:52:20	VERBOSE	"RCON sending (94.23.216.127:28970) 'set g_logsync 1'"
150915 19:52:20	VERBOSE	'No readable socket'
150915 19:52:20	VERBOSE	"RCON sending (94.23.216.127:28970) 'fs_game'"
150915 19:52:21	VERBOSE	'No readable socket'
150915 19:52:21	DEBUG	'Get cvar fs_game = []'
150915 19:52:21	WARNING	'Could not query server for fs_game'
150915 19:52:21	VERBOSE	"RCON sending (94.23.216.127:28970) 'fs_basepath'"
150915 19:52:22	VERBOSE	'No readable socket'
150915 19:52:22	DEBUG	'Get cvar fs_basepath = []'
150915 19:52:22	WARNING	'Could not query server for fs_basepath'
150915 19:52:22	VERBOSE	"RCON sending (94.23.216.127:28970) 'fs_homepath'"
150915 19:52:23	VERBOSE	'No readable socket'
150915 19:52:23	DEBUG	'Get cvar fs_homepath = []'
150915 19:52:23	WARNING	'Could not query server for fs_homepath'
150915 19:52:23	VERBOSE	"RCON sending (94.23.216.127:28970) 'shortversion'"
150915 19:52:24	VERBOSE	'No readable socket'
150915 19:52:24	DEBUG	'Get cvar shortversion = []'
150915 19:52:24	WARNING	'Could not query server for shortversion'
150915 19:52:24	DEBUG	'Parser started.'
150915 19:52:24	VERBOSE	"RCON sending (94.23.216.127:28970) 'sv_hostname'"
150915 19:52:24	VERBOSE	'No readable socket'
150915 19:52:24	DEBUG	'Get cvar sv_hostname = []'
150915 19:52:24	WARNING	'Could not query server for sv_hostname'
150915 19:52:24	BOT    	'Starting plugins'
150915 19:52:24	VERBOSE	"RCON sending (94.23.216.127:28970) 'say ^0(^2b3^0)^7: ^8www.bigbrotherbot.net ^0(^8b3^0) ^9v1.9.2 [nt] ^9[^3PoisonIvy^9]^3 ^2[ONLINE]'"
150915 19:52:24	INFO	'STDOUT "Error: \'admin\'"'
150915 19:52:24	INFO	"STDOUT '\\n'"
150915 19:52:24	ERROR	"STDERR 'Traceback (most recent call last):\\n'"
150915 19:52:24	ERROR	'STDERR \'  File "b3\\\\__init__.pyo", line 182, in start\\n\''
150915 19:52:24	ERROR	'STDERR \'  File "b3\\\\parser.pyo", line 520, in start\\n\''
150915 19:52:24	ERROR	'STDERR \'  File "b3\\\\parser.pyo", line 780, in startPlugins\\n\''
150915 19:52:24	ERROR	'STDERR \'  File "b3\\\\parser.pyo", line 770, in start_plugin\\n\''
150915 19:52:24	ERROR	'STDERR "KeyError: \'admin\'\\n"'
150915 19:52:25	VERBOSE	'No readable socket'
```

**Comment by danielepantaleone** [comment]
Commands do not work because the admin plugin is not being loaded because of the dbms connection failing. What you can do is upgrade your B3 to version [1.10.6 beta](https://github.com/BigBrotherBot/big-brother-bot/releases/tag/v1.10.6) which makes use of pymysql (and as stated [here](https://github.com/scalyr/PyMySQL/commit/38676f8d3987774a1a489b3c35368977e22149bd) support for ipv6 has been added and should work).

**Comment by MLWALK3R** [comment]
Tested that version that version also fails.

```
150915 22:35:18 BOT      'www.bigbrotherbot.net (b3) v1.10.6 [AngryBiscuit] [nt32]'
150915 22:35:18 BOT      'Python: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]'
150915 22:35:18 BOT      'Default encoding: ascii'
150915 22:35:18 BOT      'Starting Cod6Parser v0.7 for server 94.23.216.127:28970 (autorestart = OFF)'
150915 22:35:18 BOT      '--------------------------------------------'
150915 22:35:18 BOT      'Connecting to MySQL database: mysql://db778:******@2001:41d0:d:2238::db:1/db778...'
150915 22:35:20 ERROR    'Database connection failed: working in remote mode: (2003, "Can\'t connect to MySQL server on \'2001\' ([Errno 11001] getaddrinfo failed)") - [(\'c:\\\\jenkins_slave\\\\workspace\\\\B3-beta-release\\\\b3\\\\storage\\\\mysql.py\', 287, \'connect\', None), (\'C:\\\\Python27\\\\lib\\\\site-packages\\\\pymysql\\\\__init__.py\', 88, \'Connect\', None), (\'C:\\\\Python27\\\\lib\\\\site-packages\\\\pymysql\\\\connections.py\', 644, \'__init__\', None), (\'C:\\\\Python27\\\\lib\\\\site-packages\\\\pymysql\\\\connections.py\', 869, \'_connect\', None)]'
150915 22:35:20 BOT      'Game log is: C:\\TCAFiles\\Users\\mlwalk3r\\778\\data\\games_mp.log'
150915 22:35:20 BOT      u'Starting bot reading file: C:\\TCAFiles\\Users\\mlwalk3r\\778\\data\\games_mp.log'
150915 22:35:20 BOT      'Rcon status cache expire time: [2 sec] Type: [False]'
150915 22:35:20 BOT      'Game name is: cod6'
150915 22:35:20 VERBOSE  "RCON sending (94.23.216.127:28970) 'status'"
150915 22:35:21 BOT      u'Loading plugins (external plugin directory: C:\\TCAFiles\\Users\\mlwalk3r\\778\\b3\\extplugins)'
150915 22:35:21 WARNING  u'Could not find specified configuration file conf\\plugin_admin.xml for plugin admin'
150915 22:35:21 ERROR    'Could not load plugin admin'
```

**Comment by danielepantaleone** [comment]
Well there's nothing we can fix on our side. You can make use of an SQLite database. I can see from your log file that you also have a problem in your b3 configuration (plugin admin config seems missing).

**Comment by MLWALK3R** [comment]
Hmm was IPv6 support tested? and "plugin admin config seems missing" not really important when the db doesn't connect.

**Comment by danielepantaleone** [comment]
You should ask to pymysql developers about that. B3 1.10 can work without a DB connection using an SQLite database (in that case it will matter).

**Comment by MLWALK3R** [comment]
Manged to get it working (on the current stable release), turns out some settings never changed in the my.cnf. listening address need to be "bind-address = :: not 0.0.0.0"

Thanks for the help.
