### ISSUE TITLE
File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins?

### ISSUE THREAD

**Issue by cjmwid** [BigBrotherBot/big-brother-bot#353]
So... Yeh? Might be a problem?

150916 04:10:59 BOT      'www.bigbrotherbot.net (b3) v1.10.7 [AngryBiscuit] [nt32]'
150916 04:10:59 BOT      'Python: 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]'
150916 04:10:59 BOT      'Default encoding: ascii'
150916 04:10:59 BOT      'Starting Cod4Parser v1.5.1 for server (autorestart = OFF)'
150916 04:10:59 BOT      '--------------------------------------------'
150916 04:10:59 BOT      'Connecting to MySQL database: 
150916 04:10:59 BOT      'Successfully established a connection with MySQL database'
150916 04:10:59 BOT      'Game log is: D:\\Server 7(eu1)\\main\\games_mp.log'
150916 04:10:59 BOT      u'Starting bot reading file: D:\\Server 7(eu1)\\main\\games_mp.log'
150916 04:10:59 BOT      'Rcon status cache expire time: [2 sec] Type: [False]'
150916 04:10:59 BOT      'Game name is: cod4'
150916 04:10:59 VERBOSE  "RCON sending () 'status'"
150916 04:11:00 BOT      u'Loading plugins (external plugin directory: D:\\1.10.7\\extplugins)'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_spamcontrol.xml for plugin spamcontrol'
150916 04:11:00 ERROR    'Could not load plugin spamcontrol'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin spamcontrol cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_admin.xml for plugin admin'
150916 04:11:00 ERROR    'Could not load plugin admin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin admin cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_stats.xml for plugin stats'
150916 04:11:00 ERROR    'Could not load plugin stats'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin stats cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_pingwatch.xml for plugin pingwatch'
150916 04:11:00 ERROR    'Could not load plugin pingwatch'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin pingwatch cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_adv.xml for plugin adv'
150916 04:11:00 ERROR    'Could not load plugin adv'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin adv cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_status.xml for plugin status'
150916 04:11:00 ERROR    'Could not load plugin status'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin status cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_welcome.xml for plugin welcome'
150916 04:11:00 ERROR    'Could not load plugin welcome'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin welcome cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\1.10.7\\extplugins\\conf\\plugin_chatlogger.xml for plugin chatlogger'
150916 04:11:00 ERROR    'Could not load plugin chatlogger'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin chatlogger cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\1.10.7\\extplugins\\conf\\xlrstats.xml for plugin xlrstats'
150916 04:11:00 ERROR    'Could not load plugin xlrstats'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin xlrstats cannot be loaded without a configuration file'
150916 04:11:00 VERBOSE  'Servermonitor is not a built-in plugin (No module named servermonitor)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin servermonitor'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named servermonitor
150916 04:11:00 VERBOSE  'Superadmin is not a built-in plugin (No module named superadmin)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin superadmin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named superadmin
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_banlist.xml for plugin banlist'
150916 04:11:00 ERROR    'Could not load plugin banlist'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin banlist cannot be loaded without a configuration file'
150916 04:11:00 VERBOSE  'Website is not a built-in plugin (No module named website)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin website'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named website
150916 04:11:00 VERBOSE  'Openbanter is not a built-in plugin (No module named openbanter)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin openbanter'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named openbanter
150916 04:11:00 VERBOSE  'Aimbotdetector is not a built-in plugin (No module named aimbotdetector)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin aimbotdetector'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named aimbotdetector
150916 04:11:00 VERBOSE  'Asciikick is not a built-in plugin (No module named asciikick)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin asciikick'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named asciikick
150916 04:11:00 VERBOSE  'Namechangers is not a built-in plugin (No module named namechangers)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin namechangers'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named namechangers
150916 04:11:00 VERBOSE  'Tagprotect is not a built-in plugin (No module named tagprotect)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin tagprotect'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named tagprotect
150916 04:11:00 VERBOSE  'Calladmin is not a built-in plugin (No module named calladmin)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin calladmin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named calladmin
150916 04:11:00 VERBOSE  'Hackban is not a built-in plugin (No module named hackban)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin hackban'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named hackban
150916 04:11:00 CRITICAL 'Plugin admin is essential and MUST be loaded! Cannot continue without admin plugin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named hackban

Attach images by dragging & dropping,  Choose Files selecting them, or pasting from the clipboard.) 'status'"
150916 04:11:00 BOT      u'Loading plugins (external plugin directory: D:\\1.10.7\\extplugins)'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_spamcontrol.xml for plugin spamcontrol'
150916 04:11:00 ERROR    'Could not load plugin spamcontrol'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin spamcontrol cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_admin.xml for plugin admin'
150916 04:11:00 ERROR    'Could not load plugin admin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin admin cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_stats.xml for plugin stats'
150916 04:11:00 ERROR    'Could not load plugin stats'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin stats cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_pingwatch.xml for plugin pingwatch'
150916 04:11:00 ERROR    'Could not load plugin pingwatch'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin pingwatch cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_adv.xml for plugin adv'
150916 04:11:00 ERROR    'Could not load plugin adv'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin adv cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_status.xml for plugin status'
150916 04:11:00 ERROR    'Could not load plugin status'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin status cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_welcome.xml for plugin welcome'
150916 04:11:00 ERROR    'Could not load plugin welcome'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin welcome cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\1.10.7\\extplugins\\conf\\plugin_chatlogger.xml for plugin chatlogger'
150916 04:11:00 ERROR    'Could not load plugin chatlogger'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin chatlogger cannot be loaded without a configuration file'
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\1.10.7\\extplugins\\conf\\xlrstats.xml for plugin xlrstats'
150916 04:11:00 ERROR    'Could not load plugin xlrstats'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin xlrstats cannot be loaded without a configuration file'
150916 04:11:00 VERBOSE  'Servermonitor is not a built-in plugin (No module named servermonitor)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin servermonitor'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named servermonitor
150916 04:11:00 VERBOSE  'Superadmin is not a built-in plugin (No module named superadmin)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin superadmin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named superadmin
150916 04:11:00 WARNING  u'Could not find specified configuration file D:\\plugin_banlist.xml for plugin banlist'
150916 04:11:00 ERROR    'Could not load plugin banlist'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 861, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 838, in _get_plugin_config
ConfigFileNotFound: 'plugin banlist cannot be loaded without a configuration file'
150916 04:11:00 VERBOSE  'Website is not a built-in plugin (No module named website)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin website'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named website
150916 04:11:00 VERBOSE  'Openbanter is not a built-in plugin (No module named openbanter)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin openbanter'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named openbanter
150916 04:11:00 VERBOSE  'Aimbotdetector is not a built-in plugin (No module named aimbotdetector)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin aimbotdetector'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named aimbotdetector
150916 04:11:00 VERBOSE  'Asciikick is not a built-in plugin (No module named asciikick)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin asciikick'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named asciikick
150916 04:11:00 VERBOSE  'Namechangers is not a built-in plugin (No module named namechangers)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin namechangers'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named namechangers
150916 04:11:00 VERBOSE  'Tagprotect is not a built-in plugin (No module named tagprotect)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin tagprotect'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named tagprotect
150916 04:11:00 VERBOSE  'Calladmin is not a built-in plugin (No module named calladmin)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin calladmin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named calladmin
150916 04:11:00 VERBOSE  'Hackban is not a built-in plugin (No module named hackban)'
150916 04:11:00 VERBOSE  u'Trying external plugin directory : D:\\1.10.7\\extplugins'
150916 04:11:00 ERROR    'Could not load plugin hackban'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named hackban
150916 04:11:00 CRITICAL 'Plugin admin is essential and MUST be loaded! Cannot continue without admin plugin'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-beta-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named hackban

Its all in D:\1.10.7\ but keeps for config files in D:\?

**Comment by danielepantaleone** [comment]
Seems that you have not installed your extplugins correctly and also plugins configuration files seems not the be found. Fo such issues please use the forum: http://forum.bigbrotherbot.net/ . Github issues are intended to be code related problem, while your is a simple configuration one. Please open a topic on the forum posting your b3 configuration file (mask your oasswirds first).
