### ISSUE TITLE
v1.10.10 Geowelcome is not a built-in plugin

### ISSUE THREAD

**Issue by aboalwi** [BigBrotherBot/big-brother-bot#364]
uncommented geowelcome yet it doesn't work

b3 log file:
```
10:05:54 VERBOSE  'Geowelcome is not a built-in plugin (No module named welcome)'
10:05:54 VERBOSE  u'Trying external plugin directory : C:\\B3\\extplugins'
10:05:54 ERROR    'Could not load plugin geowelcome'
Traceback (most recent call last):
  File "c:\jenkins_slave\workspace\B3-stable-release\b3\parser.py", line 859, in loadPlugins
  File "c:\jenkins_slave\workspace\B3-stable-release\b3\parser.py", line 1076, in pluginImport
ImportError: No module named geowelcome
```

**Comment by danielepantaleone** [comment]
The geowelcome plugin has always give this type of error. Could you make use of the Location plugin to achieve a similar behavior (i.e: display the country of connecting players)? I don't expect a fix to come in the next few months since the project is not maintained anymore as it used to.

**Comment by aboalwi** [comment]
It's OK don't bother I'm using normal welcome plugin. Heck it's a luxury to
have. Have a good day sir.

**Comment by ShikiTheUndead** [comment]
I know this is 3 years too late, but for anyone having this issue have you tried adding the direct path such as. 

`import time
import threading

import sys
sys.path.insert(1, 'D:\B3\plugins\welcome')

from b3.functions import getCmd
from b3.plugins.welcome import WelcomePlugin
from b3.plugins.welcome import F_FIRST
from b3.plugins.welcome import F_NEWB
from b3.plugins.welcome import F_USER
from b3.plugins.welcome import F_ANNOUNCE_FIRST
from b3.plugins.welcome import F_ANNOUNCE_USER
from b3.plugins.welcome import F_CUSTOM_GREETING


class GeowelcomePlugin(WelcomePlugin):
`

**Comment by BestNoob** [comment]
> 
> 
> I know this is 3 years too late, but for anyone having this issue have you tried adding the direct path
> in the geowelcome **init**.py file such as:
> 
> `import time
> import threading
> 
> import sys
> sys.path.insert(1, 'C:\B3\plugins\welcome')
> 
> from b3.functions import getCmd
> from b3.plugins.welcome import WelcomePlugin
> from b3.plugins.welcome import F_FIRST
> from b3.plugins.welcome import F_NEWB
> from b3.plugins.welcome import F_USER
> from b3.plugins.welcome import F_ANNOUNCE_FIRST
> from b3.plugins.welcome import F_ANNOUNCE_USER
> from b3.plugins.welcome import F_CUSTOM_GREETING
> 
> class GeowelcomePlugin(WelcomePlugin):
> `

Why and how should this help ?

There is a general issue because .... :

Welcome is creating the class:
class WelcomePlugin(b3.plugin.Plugin)

and geowelcome is creating it to ?
class GeowelcomePlugin(WelcomePlugin)

if it is a build in plugin shouldnt it be:
class GeowelcomePlugin(b3.plugin.Plugin)

it trys to load "geowelcome and welcome
ERROR    'Could not load plugin geowelcome'
ImportError: No module named welcome

but none is creating it ........... so how the f**** should it work xD ???
