### ISSUE TITLE
BFBC2 Issues 223 and Errno 10061

### ISSUE THREAD

**Issue by BestNoob** [BigBrotherBot/big-brother-bot#398]
I can connect and play on server and BFBC2CC and Procon can connect and running.
But B3 Bigbrotherbot wont run.

Hope you can help me.

Console Printout
Loading Plugins : ..................... (19)
223
press any key to continue ...

BFBC2 EXE:
-port 11111 -numGameClientSlots 32 -region EU -heartBeatInterval 20000 -ServerAdminLogs 1 -StatusLogs 1 -displayAsserts 1 -displayErrors 1 -crashDumpErrors 1 -mapPack2Enabled 1

ServerOptions.ini :

Port = 11111
RemoteAdminPort = 22222
RemoteAdminPassword = 1234

B3 Config:
<set name="rcon_password">1234</set>
<set name="port">11111</set>
<set name="game_log">C:\XXXXXXX\XXXXX\RuntimeLog_XXXXXXXXX_server.log</set>
<set name="rcon_ip">127.0.0.1</set>

But i always recieve:
190312 23:00:24 VERBOSE  'RCON: connecting to Frostbite server ...'
190312 23:00:24 DEBUG    'opening FrostbiteConnection socket'
190312 23:00:25 INFO     "STDOUT 'ERROR: [Errno 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte'"
190312 23:00:25 INFO     "STDOUT '\\n'"
190312 23:00:25 ERROR    "STDERR 'Traceback (most recent call last):\\n'"
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\__init__.py", line 328, in start\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parser.py", line 468, in start\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\bfbc2.py", line 131, in startup\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\frostbite\\\\abstractParser.py", line 115, in startup\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\bfbc2.py", line 180, in checkVersion\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\frostbite\\\\rcon.py", line 79, in write\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\frostbite\\\\rcon.py", line 63, in _connect\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\frostbite\\\\connection.py", line 75, in __init__\\n\''
190312 23:00:25 ERROR    'STDERR \'  File "C:\\\\Users\\\\jenkins\\\\Downloads\\\\big-brother-bot\\\\b3\\\\parsers\\\\frostbite\\\\connection.py", line 93, in _connect\\n\''
190312 23:00:25 ERROR    "STDERR 'FrostbiteException: [Errno 10061] Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte\\n'"
190312 23:00:25 DEBUG    'closing FrostbiteConnection socket'
190312 23:00:31 BOT      'Shutting down...'
190312 23:00:31 INFO     'StatusPlugin: B3 stop/exit.. updating status'
190312 23:00:31 DEBUG    'StatusPlugin: writing XML status to ~/status.xml'
190312 23:00:31 ERROR    "[Errno 2] No such file or directory: '~/status.xml'

**Comment by BestNoob** [comment]
German: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte
English Translation: **Unable to connect because the target computer refused to connect**

**Comment by 82ndab-Bravo17** [comment]
Try setting the B3 port to the remote admin port

**Comment by LonerKO** [comment]
set name=rcon_ip 127.0.0.1 - change 127.0.0.1 to outer ip
