### ISSUE TITLE
xlrstats/echelon is not working because of timeouts

### ISSUE THREAD

**Issue by BestNoob** [BigBrotherBot/big-brother-bot#400]
Hello, its me ... again ^^

i found a problem with B3 and xlrstats, b3 gives me errors when i activate xlrstats and use some commands. Than i tried to setup echelon but without success, i have always time out errors with this.

But i think i found the problem: ist xlrstats\app\tmp

A instalaltion that was sucessfully used before is working, the reason seems to be that a fresh installation cannot verify the xlrstats keys and the installation cannot contact xlrstats service and has time outs.

**I want to ask you guys now maybe you have a solution for this, the files inside
xlrstats\app\tmp

seems to handle the connection with xlrstats service approval of the key and other parts.
How can i manually add the lines to get this working and stop xlrstats from trying to reach xlrstats service ?**

Thank you.

**Comment by BestNoob** [comment]
One of the xlrstats guys was so awesome and pushed a fix https://github.com/XLRstats/xlrstats-web-v3/commit/beecd3d327d2a0054e0ebb0f05856931a5c173d5

for the xlrstats problem, and also this Fork is a more updated one https://github.com/LandGame/xlrstats-web-v3

The question is can one of you guys here fix the xlrstats problem inside B3 ? I cannot allocate and target it, but seems to be also an timeout because of a no longer reachable webadress/service.

**Comment by 82ndab-Bravo17** [comment]
What errors do you get?

**Comment by obteo** [comment]
Hello, I'm having this error:
`190321 12:31:22 DEBUG    "XlrstatsPlugin: purgin players who haven't been online for 365 days..."
190321 12:31:22 ERROR    'Query failed [SELECT clients.id, clients.time_edit, xlr_playerstats.client_id, xlr_playerstats.id as player_id FROM clients, xlr_playerstats\n               WHERE clients.id = xlr_playerstats.client_id\n               AND 1553167882 - clients.time_edit > 31536000] None: (1690, u"BIGINT UNSIGNED value is out of range in \'(1553167882 - `admin_b3_new`.`clients`.`time_edit`)\'")'
190321 12:31:22 ERROR    'Could not start plugin xlrstats'
Traceback (most recent call last):
  File "/home/b2k/cod4/bot/b3/parser.py", line 1105, in startPlugins
    start_plugin(self, plugin_name)
  File "/home/b2k/cod4/bot/b3/parser.py", line 1096, in start_plugin
    p.onStartup()
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 256, in onStartup
    self.purgePlayers()
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 1613, in purgePlayers
    cursor = self.query(q)
  File "/home/b2k/cod4/bot/b3/storage/common.py", line 633, in query
    raise e`

**Comment by 82ndab-Bravo17** [comment]
Obteo, It looks like you may have a bad value in one of the time_edit fields in the clients table and its got a date that the server thinks is in the future. Check the server date is correct, and hasn't got set to some time in the past and if not use phpmyadmin or similar and look for a value that is bigger than 1553167882 in that field.

As a temporary fix you could turn off purging and see if that allows xlrstats to start

**Comment by obteo** [comment]
Oki thanks for the reply. the only one whith that field bigger was WORLD... :/ i edited it and now seems there is another issue because it doesnt start:

190322 17:22:44 ERROR    'Could not start plugin xlrstats'
Traceback (most recent call last):
  File "/home/b2k/cod4/bot/b3/parser.py", line 1105, in startPlugins
    start_plugin(self, plugin_name)
  File "/home/b2k/cod4/bot/b3/parser.py", line 1096, in start_plugin
    p.onStartup()
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 273, in onStartup
    mapstats = self.get_MapStats(self.console.game.mapName)
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 608, in get_MapStats
    assert name is not None

**Comment by 82ndab-Bravo17** [comment]
Are you using the compiled version or source code version?

**Comment by obteo** [comment]
I think source code and yes it was running. thank you.

**Comment by 82ndab-Bravo17** [comment]
No sure why the COD4 server isn't giving you the map name, that shouldn't happen. Does B3 run OK without xlrstats plugin loaded?

If you still have difficulty you can get an edited copy of the xlrststs plugin from my repo at https://github.com/82ndab-Bravo17/big-brother-bot/tree/xlrstats_no_assert

**Comment by miltann** [comment]
does the current version of b3 not freeze with xlrstats enabled?
