### ISSUE TITLE
XLRStats error

### ISSUE THREAD

**Issue by obteo** [BigBrotherBot/big-brother-bot#403]
Hi everyone! I can't figure out why but B3 stopped working... the only error I see is:

  File "/home/b2k/cod4/bot/b3/parser.py", line 1105, in startPlugins
    start_plugin(self, plugin_name)
  File "/home/b2k/cod4/bot/b3/parser.py", line 1096, in start_plugin
    p.onStartup()
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 273, in onStartup
    mapstats = self.get_MapStats(self.console.game.mapName)
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 608, in get_MapStats
    assert name is not None
AssertionError

but seems nothing is working at server, even the !b3 command don't shows anything... thank you for help!

**Comment by 82ndab-Bravo17** [comment]
For some reason your cod4 appears to not be giving the map name.

See the branch at https://github.com/82ndab-Bravo17/big-brother-bot/tree/xlrstats_no_assert for a new xlrstats plugin

**Comment by obteo** [comment]
Hi thanks for the reply, I tryed editing that file but it doens't start same error:

190524 11:34:17 ERROR    'Could not start plugin xlrstats'
Traceback (most recent call last):
  File "/home/b2k/cod4/bot/b3/parser.py", line 948, in startPlugins
    start_plugin(self, plugin_name)
  File "/home/b2k/cod4/bot/b3/parser.py", line 939, in start_plugin
    p.onStartup()
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 278, in onStartup
    mapstats = self.get_MapStats(self.console.game.mapName)
  File "/home/b2k/cod4/bot/b3/plugins/xlrstats/__init__.py", line 613, in get_MapStats
    assert name is not None

**Comment by 82ndab-Bravo17** [comment]
The Assert is still there, and it looks like you are using a different copy of the plugin since the line numbers have changed. Edit the original file that you had again, and change the Assert line to match the changes I did in my version.

**Comment by obteo** [comment]
maybe I copied badly what u edited, is there the downloadable file? Thanks
