### ISSUE TITLE
ERROR    'Query failed [SELECT clients.time_edit, MAX(xlr_playerstats.skill) 

### ISSUE THREAD

**Issue by obteo** [BigBrotherBot/big-brother-bot#420]
hello everybody, I'm getting this error any idea please?

```
210108 03:36:36 ERROR    'Query failed [SELECT clients.time_edit, MAX(xlr_playerstats.skill) AS max_skill FROM clients, xlr_playerstats WHERE 1610094996 - clients.time_edit <= 1728000] None: (1140, u"In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column \'proclans_b3.clients.time_edit\'; this is incompatible with sql_mode=only_full_group_by")'
210108 03:36:36 ERROR    'Could not start plugin xlrstats'
Traceback (most recent call last):
  File "/home/pa/cod4-693/bot/b3/parser.py", line 948, in startPlugins
    start_plugin(self, plugin_name)
  File "/home/pa/cod4-693/bot/b3/parser.py", line 939, in start_plugin
    p.onStartup()
  File "/home/pa/cod4-693/bot/b3/plugins/xlrstats/__init__.py", line 264, in onStartup
    self.calculateKillBonus()
  File "/home/pa/cod4-693/bot/b3/plugins/xlrstats/__init__.py", line 1519, in calculateKillBonus
    cursor = self.query(q)
  File "/home/pa/cod4-693/bot/b3/storage/common.py", line 635, in query
    raise e
InternalError: (1140, u"In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'proclans_b3.clients.time_edit'; this is incompatible with sql_mode=only_full_group_by")
```

thanks!

**Comment by obteo** [comment]
Hi! fixed it by removing the ONLY_FULL_GROUP_BY, from variabilies in mysql

**Comment by obteo** [comment]
any idea regarding this:

`210108 10:39:51 ERROR    'Exception raised while executing crontab <bound method StatusPlugin.update of <status.StatusPlugin object at 0x157e9d0>>: \'NoneType\' object has no attribute \'sendall\'\n[(\'/home/pa/cod4-693/bot/b3/cron.py\', 360, \'run\', \'c.run()\'), (\'/home/pa/cod4-693/bot/b3/cron.py\', 268, \'run\', \'CronTab.run(self)\'), (\'/home/pa/cod4-693/bot/b3/cron.py\', 85, \'run\', \'self.command()\'), (\'/home/pa/cod4-693/bot/b3/plugins/status/__init__.py\', 473, \'update\', \'self.writeXML(xml.toprettyxml(encoding="UTF-8", indent="        "))\'), (\'/home/pa/cod4-693/bot/b3/plugins/status/__init__.py\', 506, \'writeXML\', "ftp.cwd(os.path.dirname(self._ftpinfo[\'path\']))"), (\'/usr/lib/python2.7/ftplib.py\', 550, \'cwd\', \'return self.voidcmd(cmd)\'), (\'/usr/lib/python2.7/ftplib.py\', 248, \'voidcmd\', \'self.putcmd(cmd)\'), (\'/usr/lib/python2.7/ftplib.py\', 178, \'putcmd\', \'self.putline(line)\'), (\'/usr/lib/python2.7/ftplib.py\', 173, \'putline\', \'self.sock.sendall(line)\')]'`
